import { GeneTargetObject } from "@/types/gene";

// Reference fixture: Duchenne Muscular Dystrophy / DMD gene.
// Used as a local fallback so the UI is fully demoable before the
// Ensembl/NCBI/UniProt/ClinVar/GTEx/Reactome/STRING/PubMed connectors
// (see backend/connectors/*) are wired up to backend/api.
export const MOCK_GENES: Record<string, GeneTargetObject> = {
  DMD: {
    organism: "Homo sapiens (Human)",
    diseaseName: "Duchenne Muscular Dystrophy",
    geneSymbol: "DMD",

    geneName: "Dystrophin",
    geneFunction: "Dystrophin helps stabilize muscle fibers by linking the internal cytoskeleton to the surrounding extracellular matrix.",
    geneId: "1756 (NCBI)",
    entrezGeneId: "1756",
    hgncId: "HGNC:2928",
    chromosome: "X",
    location: "Xp21.2 (32,315,120-33,023,971)",
    cytoband: "Xp21.2–Xp21.1",
    genomeBuild: "GRCh38",
    genomicStart: 31097677,
    genomicEnd: 33339609,
    strand: "Reverse (−)",
    geneType: "protein_coding",
    synonyms: ["Dystrophin", "CMD3D", "BMD"],
    source: ["HGNC", "NCBI", "Ensembl"],
    taxonId: "9606",

    canonicalTranscript: "NM_004006.3",
    canonicalTranscriptLabel: "MANE",
    otherTranscripts: [
      "ENST00000357033.8",
      "ENST00000618900.1",
      "ENST00000493490.8",
      "ENST00000422878.6",
    ],
    totalTranscripts: 23,

    variantExamples: [
      { label: "c.8713C>T (p.Arg2905Ter)", source: "ClinVar" },
      { label: "c.123del (p.Leu42Argfs*18)", source: "ClinVar" },
      { label: "rs1803852", source: "dbSNP" },
    ],
    totalKnownVariantsClinvar: 12531,

    defaultTissue: "Skeletal Muscle",
    tissueExpressionLevel: "High",
    tissueTpm: 45.7,
    topTissues: [
      { name: "Skeletal Muscle", tpm: 45.7 },
      { name: "Heart Left Ventricle", tpm: 31.2 },
      { name: "Nerve Tibial", tpm: 28.5 },
    ],

    defaultCellType: "Myocyte",
    cellExpressionLevel: "High",
    cellTpm: 52.3,
    cellTypeAll: { Myocyte: 52.3, "Satellite Cell": 12.1, Fibroblast: 3.2 },

    expressionStabilityCV: 0.68,
    vitalOrganTpm: 31.2,
    vitalOrganTissues: ["Heart Left Ventricle"],
    dominantIsoformFraction: 0.87,
    dominantIsoformId: "ENST00000357033.9",
    diseaseFoldChange: 2.45,
    singleCellPrevalence: 0.72,
    circadianAmplitude: "Low Fluctuation (Acyclic)",
    intronRetentionRatio: 0.34,
    developmentalExpression: "Ubiquitous (Age-Stable)",
    alternativePolyadenylation: "Multiple 3' UTR Isoforms (44 transcripts)",
    nuclearRetentionIndex: 0.32,

    proteinId: "P11532",
    proteinName: "Dystrophin",
    proteinLength: 3685,
    molecularWeight: "426,778 Da",
    isoelectricPoint: "5.44",
    secondaryStructureDistribution: "35 helices, 9 beta strands, 6 turns",
    criticalPhosphorylationSite: "13x Phosphoserine; 5x Phosphothreonine",
    ubiquitinationTarget: "4x Ubiquitinyl lysine",
    quaternaryStructure: "Monomer",
    stabilityScore: "8.2/10, 4 disulfide bonds, 3 known variants",
    subcellularLocation: "Cytoplasm; Cell membrane; Sarcolemma",
    criticalFunctionalDomains: "Actin-binding; Zinc finger; WW domain",
    disorderedContent: "89 residues (23%)",
    proteosomalTurnover: "Chain (1-3685)",
    alphafoldPlddt: "75.1 (High Confidence)",
    gravyIndex: "-0.542 (Slightly Hydrophilic)",
    proteinAbundance: null,
    tractability: "Undruggable (Ideal ASO Target)",

    interproId: "IPR001589",
    pfamId: "PF00307",
    pdbId: "1DXX",
    mutationRate: null,
    uniprotAccession: "P11532",

    diseaseAssociation: "Duchenne Muscular Dystrophy",
    disease: "Duchenne Muscular Dystrophy",
    diseaseAssociationSource: ["ClinVar", "OMIM"],
    phenotypes: ["Duchenne muscular dystrophy"],
    associationStatus: "Established",
    omimId: "310200",

    diseaseMechanism: "Duchenne Muscular Dystrophy (DMD) is a rare X-linked recessive disorder caused by mutations in the dystrophin gene, leading to progressive muscle weakness. Dystrophin deficiency drives inflammation, oxidative stress, and myocardial remodeling in DMD cardiomyopathy. Out-of-frame mutations completely disrupt the genetic reading frame, leading to premature stop signals and 0% functional dystrophin (DMD). In-frame mutations preserve the reading frame, producing a shorter, partially functional protein (20–100% dystrophin expression, BMD). Long-term management benefits from early diagnosis and coordinated care involving neurology, cardiology, pulmonology, and rehabilitation. Continued research into targeted molecular interventions holds promise for improved outcomes in DMD-associated cardiomyopathy.",
    diagnosticTests: [
      "Creatine Kinase (CK) levels — 10–100× normal due to muscle cell leakage",
      "MLPA or Next-Generation Sequencing (NGS) for deletion/duplication/point mutation",
      "Muscle biopsy with immunohistochemistry if genetic testing inconclusive",
      "Echocardiography for cardiac function monitoring",
      "Pulmonary function tests (spirometry, forced vital capacity)",
      "Genetic testing for dystrophin gene mutations",
      "Serum biomarkers: cardiac troponin, NT-proBNP for cardiomyopathy detection",
      "MRI for muscle fibrosis and cardiac tissue assessment",
    ],
    clinicalSymptoms: [
      "Gowers' sign — using hands to walk up thighs when standing",
      "Waddling gait and progressive proximal weakness",
      "Severe scoliosis and lumbar lordosis from progressive weakness",
      "Diaphragm weakness leading to pulmonary hypoventilation and respiratory failure",
      "~30% of patients exhibit mild, non-progressive cognitive or learning impairments",
      "Progressive muscle wasting beginning in pelvis, thighs, and shoulders",
      "Pseudohypertrophy of calf muscles (Gastrocnemius)",
      "Delayed motor milestones (sitting, standing, walking)",
      "Loss of ambulation typically by age 10-12",
      "Cardiomyopathy and respiratory failure remain leading causes of mortality",
      "Cognitive impairment in 20-30% of patients",
      "Behavioral and attention difficulties",
    ],
    carrierManifestations: [
      "20% of female carriers experience mild-to-moderate muscle weakness",
      "~8% of female carriers develop dilated cardiomyopathy later in life",
      "Routine cardiac screening recommended for all carriers",
      "X-inactivation mosaicism determines severity of symptoms",
      "Elevated CK levels may be detected in carriers",
      "Asymptomatic carriers still at risk for cardiac complications",
    ],
    therapeuticOptions: [
      "Corticosteroids (prednisone/deflazacort) — standard of care to prolong walking and delay cardiac decline",
      "Exon skipping (eteplirsen, golodirsen, viltolarsen) — converts out-of-frame to in-frame mutations",
      "Gene therapy (delandistrogene moxeparvovec) — delivers micro-dystrophin gene to muscle cells",
      "ACE inhibitors and beta-blockers — cardioprotective therapy for cardiac management",
      "Resilient pulmonary support with mechanical ventilation",
      "Physical therapy and rehabilitation to maintain mobility and prevent contractures",
      "Cardiac MRI monitoring for early detection of cardiomyopathy",
      "Emerging therapies: mitochondrial dysfunction targets, calcium imbalance correction, anti-fibrotic interventions",
      "Multidisciplinary care: neurology, cardiology, pulmonology, rehabilitation",
      "Clinical trials: gene editing (CRISPR), stem cell therapy, myostatin inhibitors",
    ],

    exonCount: 79,
    intronCount: 78,
    cdsLength: 11088,
    geneLength: 2427852,

    dbSnpCount: 462,
    gnomadAvailable: true,
    clinvarVariantCount: 12531,

    topHgvsName: "NM_004006.3(DMD):c.1527_1530del (p.His512fs)",
    topRsId: null,
    populationFrequencyMaf: "2.4014e-04 (gnomAD)",

    gtexAvailable: true,
    humanProteinAtlasLevel: "High",
    gtexExpressionLevel: "Skeletal Muscle (45.7 TPM)",

    intolerantToLossScore: "1.00 (pLI, gnomAD)",
    recessiveConstraintZ: 2.84,
    hetExcessZ: -0.52,
    compositeConstraintIndex: 0.91,
    haploinsufficiencyScore: "0.9 (sufficient evidence for haploinsufficiency)",

    loeufDecile: "Decile 1",
    triplosensitivity: "Severe",
    activeIsoforms: 4,
    spliceSwitches: 1,
    structuralAccessibility: "62% (Favorable)",
    splicingMotifDensity: "38.2/kb (Moderate)",
    preclinicalConservation: "3/3 (Excellent)",
    gQuadruplexes: "2 Blocks Found",
    cpgDensity: "Low Risk",
    selfDimerRisk: "12/kb (Moderate)",
    polygTracts: "1 (Moderate)",
    transcriptSpecificity: "40 isoforms (Low)",
    codonUsageBias: "GC3=49.3% (Balanced)",

    // RNA half-life and gene dependency
    rnaHalflife: "5.2 h",
    rnaHalflifeHours: 5.2,
    rnaHalflifeSource: "RNAdecayCafe (Vock et al. 2025, Zenodo)",
    depmapDependency: "0.72 (Moderate)",
    depmapDependencyScore: 0.72,
    essentialGene: "Non-essential",
    depmapSource: "FAVOR (Xiong et al. 2024)",

    deepLinks: {
      ensembl: "https://ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000198947",
      ncbi: "https://ncbi.nlm.nih.gov/gene/1756",
      gtex: "https://gtexportal.org/home/gene/DMD",
      hpa: "https://proteinatlas.org/ENSG00000198947",
      clinvar: "https://ncbi.nlm.nih.gov/clinvar?term=DMD[gene]",
      kegg: "https://genome.jp/kegg-bin/show_pathway?hsa05414",
      reactome: "https://reactome.org/performQuery/RCBH-284684",
      pubmed: "https://pubmed.ncbi.nlm.nih.gov/?term=DMD+gene",
      omim: "https://omim.org/entry/300377",
      go: "https://amigo.geneontology.org/amigo/gene/SGD:S000001851",
      string: "https://string-db.org/network/9606.ENSG00000198947",
      clinicaltrials: "https://clinicaltrials.gov/search?cond=Duchenne+Muscular+Dystrophy&intr=DMD",
    },

    keggCount: 12,
    reactomeCount: 18,
    pathwayCommonsCount: 24,
    keggPathwayName: "Dilated cardiomyopathy",
    reactomePathwayName: "Muscle contraction",
    keggPathwayId: "hsa05414",
    reactomePathwayId: "R-HSA-390522",
    pathwayHighlight: "Dilated cardiomyopathy - Homo sapiens (human)",

    goBiologicalProcess: 1246,
    goMolecularFunction: 215,
    goCellularComponent: 320,
    goBiologicalProcessHighlight: "muscle contraction",
    goMolecularFunctionHighlight: "actin binding",
    goCellularComponentHighlight: "dystrophin-associated glycoprotein complex",

    stringHighConfidenceCount: 156,
    totalInteractors: 1258,
    topInteractors: [],
    mediumConfidenceCount: 423,
    experimentalCount: 89,
    databaseCount: 134,
    interactionNetworkDensity: "0.15 (Moderate)",

    pubmedArticleCount: 4823,
    reviewCount: 312,
    clinicalTrialsCount: 47,
    preprintCount: 23,
    caseReportsCount: 89,

    genomicSize: 2220932,
    mrnaLength: 11058,
    proteinMass: "3668.7 kDa",
    fdaApprovedTherapies: [
      { name: "Eteplirsen (Exondys 51)", indication: "Duchenne muscular dystrophy (exon 51 skipping)", approvalYear: "2016", source: "FDA Orange Book" },
      { name: "Golodirsen (Vyondys 53)", indication: "Duchenne muscular dystrophy (exon 53 skipping)", approvalYear: "2019", source: "FDA Orange Book" },
      { name: "Viltolarsen (Viltepso)", indication: "Duchenne muscular dystrophy (exon 53 skipping)", approvalYear: "2020", source: "FDA Orange Book" },
      { name: "Casimersen (Amondys 45)", indication: "Duchenne muscular dystrophy (exon 45 skipping)", approvalYear: "2021", source: "FDA Orange Book" },
    ],
    targetableExons: 4,
    incidence: "1 in 3,500 male births",
    orphanetCode: "ORPHA:98896",
    icd11Code: "8C99",
    orphanetDiseaseNames: ["Duchenne muscular dystrophy", "Becker muscular dystrophy"],
    knownPathogenicVariants: 3200,
    mutationBreakdown: {
      largeExonDeletions: 2400,
      largeExonDuplications: 180,
      nonsensePointMutations: 280,
      frameshiftMutations: 190,
      spliceSiteMutations: 150,
    },
  },
};

export function lookupMockGene(symbol: string): GeneTargetObject | null {
  return MOCK_GENES[symbol.trim().toUpperCase()] ?? null;
}
